title: Jinghuai DENG's Homepage
page-top-title: Jinghuai DENG
top-section-bg-text: Computer Science
home-subtitle: Jinghuai DENG&ensp;|&ensp;邓景怀
copyright-text: '&copy; Jinghuai DENG 2024-2025. All Rights Reserved.'
